version: "3"

services:
  app:
    image: siomiz/softethervpn
    #environment:
      #- USERS=user1:password1;user2:password2
      #- PSK=test
      #- HPW=test
    volumes:
      - ./vpn_server.config:/usr/vpnserver/vpn_server.config:z
    cap_add:
      - NET_ADMIN
    network_mode: "host"
    privileged: true
    ports:
      - 500:500/udp
      - 4500:4500/udp
      - 1701:1701/tcp
      - 1194:1194/udp
      - 5555:5555/tcp
